import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { Card } from 'react-bootstrap';

export default function Home() {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Card className={styles.card} style={{width: "100%", height: "700px"}}>
        <main className={styles.main}>
          <h1>Sistema de Totem</h1>
          <h2>Sicoob Unimais Centro Leste Paulista</h2>
          <div>

          </div>      

        </main>
      </Card>

    </>
  )
}
